[package]
name = "porthole-helper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Privileged D-Bus service for porthole."

[lib]
name = "porthole_helper"
path = "src/lib.rs"

[[bin]]
name = "porthole-helper"
path = "src/main.rs"

[dependencies]
async-trait.workspace = true
futures-util.workspace = true
ipnet.workspace = true
porthole-core = { path = "../porthole-core" }
zbus.workspace = true
zbus_polkit.workspace = true
tokio.workspace = true

[dev-dependencies]
libc.workspace = true
tempfile.workspace = true
tokio.workspace = true
