FROM registry.fedoraproject.org/fedora:44
RUN dnf install -y --setopt=install_weak_deps=False \
      gtk4-devel libadwaita-devel cargo rust clippy pkgconf-pkg-config \
      xorg-x11-server-Xvfb dbus-daemon gcc \
    && dnf clean all
