[package]
name = "porthole-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Command-line interface for porthole."

[[bin]]
name = "porthole"
path = "src/main.rs"

[dependencies]
porthole-core = { path = "../porthole-core" }
clap.workspace = true
libc.workspace = true
serde_json.workspace = true
tokio.workspace = true
zbus.workspace = true

[dev-dependencies]
tempfile.workspace = true
